# Generated by Django 3.0.7 on 2020-11-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.TextField(unique=True)),
                ('car_trans', models.TextField()),
                ('car_price', models.TextField()),
                ('car_img', models.TextField()),
            ],
        ),
    ]
