# Generated by Django 3.0.7 on 2020-12-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_address', models.CharField(blank=True, max_length=50, null=True)),
                ('station_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
