# Generated by Django 3.0.7 on 2020-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_address', models.TextField()),
                ('park_block', models.TextField()),
            ],
        ),
    ]
