# Generated by Django 3.0.7 on 2020-12-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={'managed': False},
        ),
    ]
