# Generated by Django 3.0.7 on 2020-12-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_auto_20201210_1900'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='park',
            table='park',
        ),
    ]
